### ISSUE TITLE
thread 'main' panicked at 'bad token: Eof', src/bin/pratt.rs:83:14

### ISSUE THREAD

**Issue by MayorUshanka** [matklad/minipratt#7]
```
[minipratt]$ export RUST_BACKTRACE=1
[minipratt]$ cargo b --bin pratt
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
[minipratt]$ cargo r --bin pratt
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/pratt`



thread 'main' panicked at 'bad token: Eof', src/bin/pratt.rs:83:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.58.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/1.58.0/library/core/src/panicking.rs:107:14
   2: pratt::expr_bp
             at ./src/bin/pratt.rs:83:14
   3: pratt::expr
             at ./src/bin/pratt.rs:61:14
   4: pratt::main
             at ./src/bin/pratt.rs:213:17
   5: core::ops::function::FnOnce::call_once
             at /rustc/1.58.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
What could be the cause of this?

**Comment by MayorUshanka** [comment]
Nevermind, I forgot to enter the input on stdin.
